import styled from 'styled-components';                                                                                                                                                            
                                                                                                                                                                                                       
    export const ModalOverlay = styled.div`                                                                                                                                                            
      position: fixed;                                                                                                                                                                                 
      top: 0;                                                                                                                                                                                          
      left: 0;                                                                                                                                                                                         
      width: 100vw;                                                                                                                                                                                    
      height: 100vh;                                                                                                                                                                                   
      background: rgba(0, 0, 0, 0.7);                                                                                                                                                                  
      backdrop-filter: blur(4px);                                                                                                                                                                      
      display: flex;                                                                                                                                                                                   
      align-items: center;                                                                                                                                                                             
      justify-content: center;                                                                                                                                                                         
      z-index: 1000;                                                                                                                                                                                   
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const ModalContainer = styled.div`                                                                                                                                                          
      background: #111827;                                                                                                                                                                             
      border: 1px solid rgba(255, 255, 255, 0.15);                                                                                                                                                     
      border-radius: 16px;                                                                                                                                                                             
      width: 90%;                                                                                                                                                                                      
      max-width: 480px;                                                                                                                                                                                
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5);                                                                                                                                                      
      overflow: hidden;                                                                                                                                                                                
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const ModalHeader = styled.div`                                                                                                                                                             
      display: flex;                                                                                                                                                                                   
      justify-content: space-between;                                                                                                                                                                  
      align-items: center;                                                                                                                                                                             
      padding: 1.25rem 1.5rem;                                                                                                                                                                         
      border-bottom: 1px solid rgba(255, 255, 255, 0.08);                                                                                                                                              
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const ModalTitle = styled.h3`                                                                                                                                                               
      font-size: 1.1rem;                                                                                                                                                                               
      font-weight: 700;                                                                                                                                                                                
      color: #ffffff;                                                                                                                                                                                  
      display: flex;                                                                                                                                                                                   
      align-items: center;                                                                                                                                                                             
      gap: 0.5rem;                                                                                                                                                                                     
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const CloseButton = styled.button`                                                                                                                                                          
      background: transparent;                                                                                                                                                                         
      border: none;                                                                                                                                                                                    
      color: #a0aec0;                                                                                                                                                                                  
      cursor: pointer;                                                                                                                                                                                 
      padding: 4px;                                                                                                                                                                                    
      display: flex;                                                                                                                                                                                   
      align-items: center;                                                                                                                                                                             
      justify-content: center;                                                                                                                                                                         
      border-radius: 4px;                                                                                                                                                                              
                                                                                                                                                                                                       
      &:hover {                                                                                                                                                                                        
        color: #ffffff;                                                                                                                                                                                
        background: rgba(255, 255, 255, 0.1);                                                                                                                                                          
      }                                                                                                                                                                                                
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const ModalBody = styled.form`                                                                                                                                                              
      padding: 1.5rem;                                                                                                                                                                                 
      display: flex;                                                                                                                                                                                   
      flex-direction: column;                                                                                                                                                                          
      gap: 1.25rem;                                                                                                                                                                                    
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const EquipmentNoticeBox = styled.div`                                                                                                                                                      
      background: rgba(255, 23, 68, 0.08);                                                                                                                                                             
      border: 1px solid rgba(255, 23, 68, 0.25);                                                                                                                                                       
      border-radius: 8px;                                                                                                                                                                              
      padding: 0.85rem;                                                                                                                                                                                
                                                                                                                                                                                                       
      .title {                                                                                                                                                                                         
        font-weight: 700;                                                                                                                                                                              
        color: #ff5252;                                                                                                                                                                                
        font-size: 0.9rem;                                                                                                                                                                             
      }                                                                                                                                                                                                
      .sub {                                                                                                                                                                                           
        font-size: 0.78rem;                                                                                                                                                                            
        color: #a0aec0;                                                                                                                                                                                
        margin-top: 2px;                                                                                                                                                                               
      }                                                                                                                                                                                                
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const FormGroup = styled.div`                                                                                                                                                               
      display: flex;                                                                                                                                                                                   
      flex-direction: column;                                                                                                                                                                          
      gap: 0.4rem;                                                                                                                                                                                     
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const FormLabel = styled.label`                                                                                                                                                             
      font-size: 0.85rem;                                                                                                                                                                              
      font-weight: 600;                                                                                                                                                                                
      color: #cbd5e0;                                                                                                                                                                                  
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const FormSelect = styled.select`                                                                                                                                                           
      width: 100%;                                                                                                                                                                                     
      padding: 0.75rem;                                                                                                                                                                                
      background: rgba(0, 0, 0, 0.4);                                                                                                                                                                  
      border: 1px solid rgba(255, 255, 255, 0.15);                                                                                                                                                     
      border-radius: 8px;                                                                                                                                                                              
      color: #ffffff;                                                                                                                                                                                  
      font-size: 0.88rem;                                                                                                                                                                              
                                                                                                                                                                                                       
      &:focus {                                                                                                                                                                                        
        outline: none;                                                                                                                                                                                 
        border-color: #00e676;                                                                                                                                                                         
      }                                                                                                                                                                                                
                                                                                                                                                                                                       
      option {                                                                                                                                                                                         
        background: #111827;                                                                                                                                                                           
        color: #ffffff;                                                                                                                                                                                
      }                                                                                                                                                                                                
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const FormTextarea = styled.textarea`                                                                                                                                                       
      width: 100%;                                                                                                                                                                                     
      padding: 0.75rem;                                                                                                                                                                                
      background: rgba(0, 0, 0, 0.4);                                                                                                                                                                  
      border: 1px solid rgba(255, 255, 255, 0.15);                                                                                                                                                     
      border-radius: 8px;                                                                                                                                                                              
      color: #ffffff;                                                                                                                                                                                  
      font-size: 0.88rem;                                                                                                                                                                              
      resize: vertical;                                                                                                                                                                                
                                                                                                                                                                                                       
      &:focus {                                                                                                                                                                                        
        outline: none;                                                                                                                                                                                 
        border-color: #00e676;                                                                                                                                                                         
      }                                                                                                                                                                                                
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const ModalFooter = styled.div`                                                                                                                                                             
      display: flex;                                                                                                                                                                                   
      justify-content: flex-end;                                                                                                                                                                       
      gap: 0.75rem;                                                                                                                                                                                    
      margin-top: 0.5rem;                                                                                                                                                                              
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const BtnCancel = styled.button`                                                                                                                                                            
      padding: 0.65rem 1.25rem;                                                                                                                                                                        
      background: rgba(255, 255, 255, 0.08);                                                                                                                                                           
      color: #cbd5e0;                                                                                                                                                                                  
      border: none;                                                                                                                                                                                    
      border-radius: 8px;                                                                                                                                                                              
      font-weight: 600;                                                                                                                                                                                
      cursor: pointer;                                                                                                                                                                                 
                                                                                                                                                                                                       
      &:hover {                                                                                                                                                                                        
        background: rgba(255, 255, 255, 0.15);                                                                                                                                                         
        color: #ffffff;                                                                                                                                                                                
      }                                                                                                                                                                                                
    `;                                                                                                                                                                                                 
                                                                                                                                                                                                       
    export const BtnSubmit = styled.button`                                                                                                                                                            
      padding: 0.65rem 1.25rem;                                                                                                                                                                        
      background: #ff1744;                                                                                                                                                                             
      color: #ffffff;                                                                                                                                                                                  
      border: none;                                                                                                                                                                                    
      border-radius: 8px;                                                                                                                                                                              
      font-weight: 700;                                                                                                                                                                                
      cursor: pointer;                                                                                                                                                                                 
      display: flex;                                                                                                                                                                                   
      align-items: center;                                                                                                                                                                             
      gap: 0.5rem;                                                                                                                                                                                     
                                                                                                                                                                                                       
      &:disabled {                                                                                                                                                                                     
        opacity: 0.4;                                                                                                                                                                                  
        cursor: not-allowed;                                                                                                                                                                           
      }                                                                                                                                                                                                
                                                                                                                                                                                                       
      &:hover:not(:disabled) {                                                                                                                                                                         
        background: #d50000;                                                                                                                                                                           
        box-shadow: 0 0 15px rgba(255, 23, 68, 0.4);                                                                                                                                                   
      }                                                                                                                                                                                                
    `;  